/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.checkout.checkout_system;

/**
 *
 * @author wolejr
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        landingPanel = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        fLoyaltyButton = new javax.swing.JButton();
        fLanguageButton = new javax.swing.JButton();
        fHelpButton = new javax.swing.JButton();
        fVisaButton = new javax.swing.JButton();
        homePanel = new javax.swing.JPanel();
        basketButton = new javax.swing.JButton();
        noBarcodeButton = new javax.swing.JButton();
        secLoyalty = new javax.swing.JButton();
        secFrench = new javax.swing.JButton();
        secHelp = new javax.swing.JButton();
        paymentTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        thirdPanel = new javax.swing.JPanel();
        basket1Button = new javax.swing.JButton();
        payButton = new javax.swing.JButton();
        barcodeButton = new javax.swing.JButton();
        loyButton = new javax.swing.JButton();
        frenButton = new javax.swing.JButton();
        helButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        paymentPanel = new javax.swing.JPanel();
        emptBaskBut = new javax.swing.JButton();
        posButton = new javax.swing.JButton();
        hBut = new javax.swing.JButton();
        frBut = new javax.swing.JButton();
        loyBut = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        finalPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        barcodePanel = new javax.swing.JPanel();
        prodNumLabel = new javax.swing.JLabel();
        productText = new javax.swing.JTextField();
        productButton = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(860, 500));
        setMinimumSize(new java.awt.Dimension(860, 500));

        backgroundPanel.setLayout(new java.awt.CardLayout());

        landingPanel.setBackground(new java.awt.Color(255, 255, 255));
        landingPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.lightGray));

        startButton.setBackground(new java.awt.Color(0, 153, 0));
        startButton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        startButton.setIcon(new javax.swing.ImageIcon("/Users/wolejr/Downloads/shoppingcartIcon.png")); // NOI18N
        startButton.setText("START");
        startButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 0), null));
        startButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        startButton.setOpaque(true);
        startButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        fLoyaltyButton.setIcon(new javax.swing.ImageIcon(((new javax.swing.ImageIcon("/Users/wolejr/Downloads/loyalty.png")).getImage()).getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH)));
        fLoyaltyButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, null));
        fLoyaltyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fLoyaltyButtonActionPerformed(evt);
            }
        });

        fLanguageButton.setIcon(new javax.swing.ImageIcon(((new javax.swing.ImageIcon("/Users/wolejr/Downloads/french.png")).getImage()).getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH)));
        fLanguageButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, null));

        fHelpButton.setIcon(new javax.swing.ImageIcon(((new javax.swing.ImageIcon("/Users/wolejr/Downloads/help.jpeg")).getImage()).getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH)));
        fHelpButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, null));

        fVisaButton.setIcon(new javax.swing.ImageIcon("/Users/wolejr/Downloads/visa.jpg")); // NOI18N
        fVisaButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout landingPanelLayout = new javax.swing.GroupLayout(landingPanel);
        landingPanel.setLayout(landingPanelLayout);
        landingPanelLayout.setHorizontalGroup(
            landingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(landingPanelLayout.createSequentialGroup()
                .addGroup(landingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(landingPanelLayout.createSequentialGroup()
                        .addGap(446, 446, 446)
                        .addComponent(fLoyaltyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fLanguageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fHelpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(landingPanelLayout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(landingPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(fVisaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        landingPanelLayout.setVerticalGroup(
            landingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(landingPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(fVisaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(landingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fLoyaltyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fLanguageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fHelpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        backgroundPanel.add(landingPanel, "card2");

        homePanel.setBackground(new java.awt.Color(255, 255, 255));
        homePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));

        basketButton.setBackground(new java.awt.Color(51, 51, 51));
        basketButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        basketButton.setForeground(new java.awt.Color(102, 102, 102));
        basketButton.setIcon(new javax.swing.ImageIcon("/Users/wolejr/Downloads/shoppingcartIcon.png")); // NOI18N
        basketButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), null));
        basketButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        basketButton.setOpaque(true);
        basketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basketButtonActionPerformed(evt);
            }
        });

        noBarcodeButton.setIcon(new javax.swing.ImageIcon(((new javax.swing.ImageIcon("/Users/wolejr/Downloads/nobarcode.png")).getImage()).getScaledInstance(200, 200, java.awt.Image.SCALE_SMOOTH)));
        noBarcodeButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(204, 204, 204)));
        noBarcodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noBarcodeButtonActionPerformed(evt);
            }
        });

        secLoyalty.setIcon(new javax.swing.ImageIcon(((new javax.swing.ImageIcon("/Users/wolejr/Downloads/loyalty.png")).getImage()).getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH)));
        secLoyalty.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));

        secFrench.setIcon(new javax.swing.ImageIcon(((new javax.swing.ImageIcon("/Users/wolejr/Downloads/french.png")).getImage()).getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH)));
        secFrench.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.gray, null));

        secHelp.setIcon(new javax.swing.ImageIcon(((new javax.swing.ImageIcon("/Users/wolejr/Downloads/help.jpeg")).getImage()).getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH)));
        secHelp.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));

        paymentTextField.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        paymentTextField.setText(" Total : $19.98");
        paymentTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        paymentTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentTextFieldActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("06038328                                                          X\n1 Pair of Jeans              MTS                           7.99\n\n06038369                                                           X\n1 Sweater                       MTS                         12.99\n");
        jScrollPane1.setViewportView(jTextArea2);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/wolejr/Downloads/rightPointer.png")); // NOI18N
        jLabel2.setText("press right button to pay");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setIconTextGap(-6);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(paymentTextField)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                        .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(homePanelLayout.createSequentialGroup()
                                .addComponent(secLoyalty, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(secFrench, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(secHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(homePanelLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(basketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                        .addComponent(noBarcodeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183))))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(basketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(homePanelLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addComponent(noBarcodeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(31, 31, 31)
                        .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(secLoyalty, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(secFrench, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(secHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(paymentTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)))
                .addGap(14, 14, 14))
        );

        backgroundPanel.add(homePanel, "card3");

        basket1Button.setBackground(new java.awt.Color(51, 102, 0));
        basket1Button.setIcon(new javax.swing.ImageIcon("/Users/wolejr/Downloads/shoppingcartIcon.png")); // NOI18N
        basket1Button.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, null));
        basket1Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        basket1Button.setIconTextGap(-20);
        basket1Button.setOpaque(true);
        basket1Button.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        basket1Button.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        payButton.setBackground(new java.awt.Color(0, 153, 102));
        payButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        payButton.setForeground(new java.awt.Color(0, 153, 102));
        payButton.setIcon(new javax.swing.ImageIcon(((new javax.swing.ImageIcon("/Users/wolejr/Downloads/payment.jpeg")).getImage()).getScaledInstance(100, 85, java.awt.Image.SCALE_SMOOTH)));
        payButton.setText("PAY");
        payButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, null));
        payButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        payButton.setOpaque(true);
        payButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });

        barcodeButton.setIcon(new javax.swing.ImageIcon("/Users/wolejr/Downloads/nobarcode.png")); // NOI18N

        loyButton.setIcon(new javax.swing.ImageIcon(((new javax.swing.ImageIcon("/Users/wolejr/Downloads/loyalty.png")).getImage()).getScaledInstance(120, 100, java.awt.Image.SCALE_SMOOTH)));
        loyButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, null));

        frenButton.setIcon(new javax.swing.ImageIcon(((new javax.swing.ImageIcon("/Users/wolejr/Downloads/french.png")).getImage()).getScaledInstance(120, 100, java.awt.Image.SCALE_SMOOTH)));
        frenButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, null));

        helButton.setIcon(new javax.swing.ImageIcon(((new javax.swing.ImageIcon("/Users/wolejr/Downloads/help.jpeg")).getImage()).getScaledInstance(120, 100, java.awt.Image.SCALE_SMOOTH)));
        helButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, null));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("06038328                                                          X\n1 Pair of Jeans              MTS                           7.99\n\n06038369                                                           X\n1 Sweater                       MTS                         12.99\n");
        jScrollPane2.setViewportView(jTextArea1);

        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setText(" \n\nTotal : $ 19.98");
        jScrollPane3.setViewportView(jTextArea3);

        javax.swing.GroupLayout thirdPanelLayout = new javax.swing.GroupLayout(thirdPanel);
        thirdPanel.setLayout(thirdPanelLayout);
        thirdPanelLayout.setHorizontalGroup(
            thirdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thirdPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(thirdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(thirdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, thirdPanelLayout.createSequentialGroup()
                        .addComponent(barcodeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(155, 155, 155))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, thirdPanelLayout.createSequentialGroup()
                        .addGroup(thirdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(thirdPanelLayout.createSequentialGroup()
                                .addComponent(loyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(frenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(helButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(thirdPanelLayout.createSequentialGroup()
                                .addComponent(basket1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(163, 163, 163)
                                .addComponent(payButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))))
        );
        thirdPanelLayout.setVerticalGroup(
            thirdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thirdPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(thirdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(thirdPanelLayout.createSequentialGroup()
                        .addGroup(thirdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(basket1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(payButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(barcodeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(thirdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(thirdPanelLayout.createSequentialGroup()
                        .addGap(0, 26, Short.MAX_VALUE)
                        .addGroup(thirdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(frenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(helButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        backgroundPanel.add(thirdPanel, "card4");

        emptBaskBut.setBackground(new java.awt.Color(153, 153, 153));
        emptBaskBut.setForeground(new java.awt.Color(153, 153, 153));
        emptBaskBut.setIcon(new javax.swing.ImageIcon(((new javax.swing.ImageIcon("/Users/wolejr/Downloads/shoppingcartIcon.png")).getImage()).getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH)));
        emptBaskBut.setOpaque(true);

        posButton.setIcon(new javax.swing.ImageIcon(((new javax.swing.ImageIcon("/Users/wolejr/Downloads/posMachine.png")).getImage()).getScaledInstance(160, 160, java.awt.Image.SCALE_SMOOTH)));
        posButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        posButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posButtonActionPerformed(evt);
            }
        });

        hBut.setIcon(new javax.swing.ImageIcon(((new javax.swing.ImageIcon("/Users/wolejr/Downloads/help.jpeg")).getImage()).getScaledInstance(120, 90, java.awt.Image.SCALE_SMOOTH)));
        hBut.setOpaque(true);

        frBut.setIcon(new javax.swing.ImageIcon(((new javax.swing.ImageIcon("/Users/wolejr/Downloads/french.png")).getImage()).getScaledInstance(120, 100, java.awt.Image.SCALE_SMOOTH)));
        frBut.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        frBut.setOpaque(true);
        frBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frButActionPerformed(evt);
            }
        });

        loyBut.setIcon(new javax.swing.ImageIcon(((new javax.swing.ImageIcon("/Users/wolejr/Downloads/loyalty.png")).getImage()).getScaledInstance(120, 100, java.awt.Image.SCALE_SMOOTH)));
        loyBut.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, null));
        loyBut.setOpaque(true);
        loyBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loyButActionPerformed(evt);
            }
        });

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jTextArea4.setText("06038328                                                          X\n1 Pair of Jeans              MTS                           7.99\n\n06038369                                                           X\n1 Sweater                       MTS                         12.99\n");
        jScrollPane4.setViewportView(jTextArea4);

        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextArea5.setRows(5);
        jTextArea5.setText(" \n\nTotal : $19.98");
        jScrollPane5.setViewportView(jTextArea5);

        javax.swing.GroupLayout paymentPanelLayout = new javax.swing.GroupLayout(paymentPanel);
        paymentPanel.setLayout(paymentPanelLayout);
        paymentPanelLayout.setHorizontalGroup(
            paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentPanelLayout.createSequentialGroup()
                        .addComponent(posButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(208, 208, 208))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentPanelLayout.createSequentialGroup()
                        .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(emptBaskBut, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(paymentPanelLayout.createSequentialGroup()
                                .addComponent(loyBut, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(frBut, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(hBut, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17))))
        );
        paymentPanelLayout.setVerticalGroup(
            paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paymentPanelLayout.createSequentialGroup()
                        .addComponent(emptBaskBut, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(posButton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 59, Short.MAX_VALUE))
                    .addComponent(jScrollPane4))
                .addGap(18, 18, 18)
                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hBut, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(frBut, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(loyBut, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        backgroundPanel.add(paymentPanel, "card5");

        finalPanel.setBackground(new java.awt.Color(255, 255, 255));
        finalPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.lightGray));
        finalPanel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Thank you! Please remove your bag and take your receipt");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout finalPanelLayout = new javax.swing.GroupLayout(finalPanel);
        finalPanel.setLayout(finalPanelLayout);
        finalPanelLayout.setHorizontalGroup(
            finalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, finalPanelLayout.createSequentialGroup()
                .addContainerGap(225, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
        );
        finalPanelLayout.setVerticalGroup(
            finalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(finalPanelLayout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(240, Short.MAX_VALUE))
        );

        backgroundPanel.add(finalPanel, "card6");

        barcodePanel.setBackground(new java.awt.Color(255, 255, 255));
        barcodePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        barcodePanel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        prodNumLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        prodNumLabel.setText("Enter Product Number");

        productText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productTextActionPerformed(evt);
            }
        });

        productButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        productButton.setText("submit");
        productButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productButtonActionPerformed(evt);
            }
        });

        errorLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        errorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout barcodePanelLayout = new javax.swing.GroupLayout(barcodePanel);
        barcodePanel.setLayout(barcodePanelLayout);
        barcodePanelLayout.setHorizontalGroup(
            barcodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barcodePanelLayout.createSequentialGroup()
                .addContainerGap(229, Short.MAX_VALUE)
                .addComponent(prodNumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(productText, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(345, 345, 345))
            .addGroup(barcodePanelLayout.createSequentialGroup()
                .addGroup(barcodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(barcodePanelLayout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(productButton))
                    .addGroup(barcodePanelLayout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        barcodePanelLayout.setVerticalGroup(
            barcodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barcodePanelLayout.createSequentialGroup()
                .addGroup(barcodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(barcodePanelLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(prodNumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barcodePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(productText, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(productButton)
                .addGap(18, 18, 18)
                .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(195, Short.MAX_VALUE))
        );

        backgroundPanel.add(barcodePanel, "card7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fLoyaltyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fLoyaltyButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fLoyaltyButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        landingPanel.setVisible(false);
        homePanel.setVisible(true);
    }//GEN-LAST:event_startButtonActionPerformed

    private void paymentTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentTextFieldActionPerformed

    private void basketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basketButtonActionPerformed
        homePanel.setVisible(false);
        thirdPanel.setVisible(true);
    }//GEN-LAST:event_basketButtonActionPerformed

    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButtonActionPerformed
        thirdPanel.setVisible(false);
        paymentPanel.setVisible(true);
    }//GEN-LAST:event_payButtonActionPerformed

    private void frButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frButActionPerformed

    private void loyButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loyButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loyButActionPerformed

    private void posButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posButtonActionPerformed
        paymentPanel.setVisible(false);
        finalPanel.setVisible(true);
    }//GEN-LAST:event_posButtonActionPerformed

    private void productTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productTextActionPerformed

    private void productButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productButtonActionPerformed
        String productID = String.valueOf(productText.getText());
   
        if(productID.equals("06038369") || productID.equals("06038328"))
        {
            errorLabel.setText("Product ID is valid!");
            barcodePanel.setVisible(false);
            homePanel.setVisible(true);

        }
        else
        {
            errorLabel.setText("Invalid Product ID!Re-enter");
            homePanel.setVisible(true);
            
        }
        
    }//GEN-LAST:event_productButtonActionPerformed

    private void noBarcodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noBarcodeButtonActionPerformed
        homePanel.setVisible(false);
        barcodePanel.setVisible(true);
    }//GEN-LAST:event_noBarcodeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new NewJFrame().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton barcodeButton;
    private javax.swing.JPanel barcodePanel;
    private javax.swing.JButton basket1Button;
    private javax.swing.JButton basketButton;
    private javax.swing.JButton emptBaskBut;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JButton fHelpButton;
    private javax.swing.JButton fLanguageButton;
    private javax.swing.JButton fLoyaltyButton;
    private javax.swing.JButton fVisaButton;
    private javax.swing.JPanel finalPanel;
    private javax.swing.JButton frBut;
    private javax.swing.JButton frenButton;
    private javax.swing.JButton hBut;
    private javax.swing.JButton helButton;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JPanel landingPanel;
    private javax.swing.JButton loyBut;
    private javax.swing.JButton loyButton;
    private javax.swing.JButton noBarcodeButton;
    private javax.swing.JButton payButton;
    private javax.swing.JPanel paymentPanel;
    private javax.swing.JTextField paymentTextField;
    private javax.swing.JButton posButton;
    private javax.swing.JLabel prodNumLabel;
    private javax.swing.JButton productButton;
    private javax.swing.JTextField productText;
    private javax.swing.JButton secFrench;
    private javax.swing.JButton secHelp;
    private javax.swing.JButton secLoyalty;
    private javax.swing.JButton startButton;
    private javax.swing.JPanel thirdPanel;
    // End of variables declaration//GEN-END:variables
}
